name: Automation Test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  automation-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Grant execute permission
        run: chmod +x gradlew

      - name: Run Automation Test
        run: ./gradlew clean test

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Test Report
          path: app/build/reports/tests/test